// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyStRMY0N-0HuupqD88JkrAx3JRmmkk4',
    appId: '1:830261260821:web:05f2ff77cd7afcda26141c',
    messagingSenderId: '830261260821',
    projectId: 'careconnect-login-75494',
    authDomain: 'careconnect-login-75494.firebaseapp.com',
    storageBucket: 'careconnect-login-75494.firebasestorage.app',
    measurementId: 'G-G3P78WM217',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSw3kQnlVs5n-JlPtejxHmDRyJo9_tfQ0',
    appId: '1:830261260821:android:72dc35b46f0c0fa926141c',
    messagingSenderId: '830261260821',
    projectId: 'careconnect-login-75494',
    storageBucket: 'careconnect-login-75494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4vrtBg1JAzkAv4_0nSerkSOq4Zhuyx7c',
    appId: '1:830261260821:ios:52777eda94142b7f26141c',
    messagingSenderId: '830261260821',
    projectId: 'careconnect-login-75494',
    storageBucket: 'careconnect-login-75494.firebasestorage.app',
    iosBundleId: 'com.example.careconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4vrtBg1JAzkAv4_0nSerkSOq4Zhuyx7c',
    appId: '1:830261260821:ios:52777eda94142b7f26141c',
    messagingSenderId: '830261260821',
    projectId: 'careconnect-login-75494',
    storageBucket: 'careconnect-login-75494.firebasestorage.app',
    iosBundleId: 'com.example.careconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNyStRMY0N-0HuupqD88JkrAx3JRmmkk4',
    appId: '1:830261260821:web:6205689748cf6db126141c',
    messagingSenderId: '830261260821',
    projectId: 'careconnect-login-75494',
    authDomain: 'careconnect-login-75494.firebaseapp.com',
    storageBucket: 'careconnect-login-75494.firebasestorage.app',
    measurementId: 'G-PXYM9L8KTY',
  );

}